version = 1

test_patterns = ["tests/**"]
exclude_patterns = ["**/testdata/**"]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/HarshCasper/tinygo"]
  cgo_enabled = false
